import express from 'express';import helmet from 'helmet';import cors from 'cors';import rateLimit from 'express-rate-limit';import cookieParser from 'cookie-parser';import {Pool} from 'pg';import {z} from 'zod';import bcrypt from 'bcryptjs';import jwt from 'jsonwebtoken';
const app=express();const pool=new Pool({connectionString:process.env.DATABASE_URL,ssl:process.env.NODE_ENV==='production'?{rejectUnauthorized:false}:false,max:10});
app.set('trust proxy',1);app.use(helmet());app.use(cors({origin:process.env.WEB_ORIGIN||'http://localhost:5173',credentials:true}));app.use(express.json({limit:'1mb'}));app.use(cookieParser());app.use(rateLimit({windowMs:15*60*1000,max:300,standardHeaders:true,legacyHeaders:false}));
const orderSchema=z.object({items:z.array(z.object({menu_item_id:z.string().uuid(),quantity:z.number().int().min(1).max(20)})).min(1).max(50)});
const JWT_SECRET=process.env.JWT_SECRET||'development-only-change-me';
function setSessionCookie(res,token){res.cookie('customer_session',token,{httpOnly:true,secure:process.env.NODE_ENV==='production',sameSite:'lax',path:'/',maxAge:12*60*60*1000});}
async function customerSession(req){const token=req.headers['x-customer-session']||req.cookies?.customer_session;if(!token)return null;const q=await pool.query('select s.id session_id,s.restaurant_id,s.table_id,t.label table_label,r.name restaurant_name from customer_sessions s join restaurant_tables t on t.id=s.table_id and t.restaurant_id=s.restaurant_id join restaurants r on r.id=s.restaurant_id where s.session_token=$1 and s.expires_at>now() and t.active=true',[token]);return q.rows[0]||null}
app.get('/health',async(_,res)=>{try{await pool.query('select 1');res.json({ok:true,service:'qr-restaurant-api'})}catch{res.status(503).json({ok:false})}});
app.get('/api/menu/:restaurantSlug/:tableToken',async(req,res)=>{try{const q=await pool.query('select r.id restaurant_id,r.name restaurant_name,r.slug,t.id table_id,t.label table_label from restaurants r join restaurant_tables t on t.restaurant_id=r.id where r.slug=$1 and t.public_token=$2 and t.active=true',[req.params.restaurantSlug,req.params.tableToken]);if(!q.rowCount)return res.status(404).json({error:'Invalid table QR'});const base=q.rows[0];const items=await pool.query('select id,name_en,name_kn,description_en,description_kn,price,image_url,category,is_available from menu_items where restaurant_id=$1 and is_available=true order by category,sort_order,name_en',[base.restaurant_id]);res.json({...base,items:items.rows});}catch(e){console.error(e);res.status(500).json({error:'Server error'})}});
async function adminAuth(req,res,next){try{const token=req.cookies?.admin_session;if(!token)return res.status(401).json({error:'Unauthorized'});const decoded=jwt.verify(token,JWT_SECRET);const q=await pool.query('select u.id user_id,rm.restaurant_id,rm.role,r.name restaurant_name from users u join restaurant_members rm on rm.user_id=u.id join restaurants r on r.id=rm.restaurant_id where u.id=$1',[decoded.sub]);if(!q.rowCount||!['owner','manager','kitchen','staff'].includes(q.rows[0].role))return res.status(403).json({error:'Forbidden'});req.admin=q.rows[0];next()}catch{return res.status(401).json({error:'Unauthorized'})}}
app.post('/api/admin/login',async(req,res)=>{try{const body=z.object({email:z.string().email().max(200),password:z.string().min(8).max(200)}).parse(req.body);const q=await pool.query('select id,password_hash from users where lower(email)=lower($1)',[body.email]);if(!q.rowCount||!(await bcrypt.compare(body.password,q.rows[0].password_hash)))return res.status(401).json({error:'Invalid credentials'});const member=await pool.query('select restaurant_id,role from restaurant_members where user_id=$1 limit 1',[q.rows[0].id]);if(!member.rowCount)return res.status(403).json({error:'No restaurant access'});const token=jwt.sign({sub:q.rows[0].id},JWT_SECRET,{expiresIn:'12h'});res.cookie('admin_session',token,{httpOnly:true,secure:process.env.NODE_ENV==='production',sameSite:'lax',path:'/',maxAge:12*60*60*1000});res.json({ok:true})}catch(e){console.error(e);res.status(400).json({error:'Invalid login request'})}});
app.post('/api/admin/logout',(req,res)=>{res.clearCookie('admin_session',{httpOnly:true,secure:process.env.NODE_ENV==='production',sameSite:'lax',path:'/'});res.json({ok:true})});
app.get('/api/admin/orders',adminAuth,async(req,res)=>{try{const q=await pool.query('select o.id,o.status,o.total,o.created_at,t.label table_label,coalesce(json_agg(json_build_object(\'name\',oi.name_snapshot,\'quantity\',oi.quantity,\'price\',oi.price_snapshot) order by oi.id) filter(where oi.id is not null),\'[]\') items from orders o join restaurant_tables t on t.id=o.table_id and t.restaurant_id=o.restaurant_id left join order_items oi on oi.order_id=o.id where o.restaurant_id=$1 and o.status<>\'served\' group by o.id,t.label order by o.created_at desc',[req.admin.restaurant_id]);res.json({restaurant_name:req.admin.restaurant_name,role:req.admin.role,orders:q.rows})}catch(e){console.error(e);res.status(500).json({error:'Unable to load orders'})}});
app.patch('/api/admin/orders/:id',adminAuth,async(req,res)=>{try{const body=z.object({status:z.enum(['accepted','preparing','ready','served','cancelled'])}).parse(req.body);const q=await pool.query('update orders set status=$1 where id=$2 and restaurant_id=$3 returning id,status',[body.status,req.params.id,req.admin.restaurant_id]);if(!q.rowCount)return res.status(404).json({error:'Order not found'});res.json(q.rows[0])}catch(e){console.error(e);res.status(400).json({error:'Invalid order update'})}});
app.post('/api/session',async(req,res)=>{try{const body=z.object({restaurantSlug:z.string().min(1).max(100),tableToken:z.string().min(20).max(100)}).parse(req.body);const q=await pool.query('select r.id restaurant_id,t.id table_id from restaurants r join restaurant_tables t on t.restaurant_id=r.id where r.slug=$1 and t.public_token=$2 and t.active=true',[body.restaurantSlug,body.tableToken]);if(!q.rowCount)return res.status(404).json({error:'Invalid table QR'});const s=await pool.query('insert into customer_sessions(restaurant_id,table_id) values($1,$2) returning session_token',[q.rows[0].restaurant_id,q.rows[0].table_id]);setSessionCookie(res,s.rows[0].session_token);res.json({ok:true})}catch(e){console.error(e);res.status(400).json({error:'Unable to start table session'})}});
app.post('/api/orders',async(req,res)=>{const client=await pool.connect();try{const session=await customerSession(req);if(!session)return res.status(401).json({error:'Table session expired'});const body=orderSchema.parse(req.body);await client.query('begin');const ids=body.items.map(x=>x.menu_item_id);const q=await client.query('select id,name_en,price from menu_items where restaurant_id=$1 and id=any($2::uuid[]) and is_available=true',[session.restaurant_id,ids]);if(q.rowCount!==ids.length){await client.query('rollback');return res.status(400).json({error:'One or more menu items are unavailable'})}const map=new Map(q.rows.map(x=>[x.id,x]));let total=0;for(const item of body.items)total+=Number(map.get(item.menu_item_id).price)*item.quantity;const order=await client.query('insert into orders(restaurant_id,table_id,session_id,status,total) values($1,$2,$3,\'received\',$4) returning id,status,total,created_at',[session.restaurant_id,session.table_id,session.session_id,total]);for(const item of body.items){const row=map.get(item.menu_item_id);await client.query('insert into order_items(order_id,menu_item_id,name_snapshot,price_snapshot,quantity) values($1,$2,$3,$4,$5)',[order.rows[0].id,row.id,row.name_en,row.price,item.quantity])}await client.query('commit');res.status(201).json({order:order.rows[0],table_label:session.table_label})}catch(e){await client.query('rollback').catch(()=>{});console.error(e);res.status(400).json({error:e instanceof z.ZodError?'Invalid order':'Could not place order'})}finally{client.release()}});
app.post('/api/service-requests',async(req,res)=>{try{const session=await customerSession(req);if(!session)return res.status(401).json({error:'Table session expired'});const body=z.object({type:z.enum(['waiter','water','bill'])}).parse(req.body);const q=await pool.query('insert into service_requests(restaurant_id,table_id,session_id,type) values($1,$2,$3,$4) returning id,type,status,created_at',[session.restaurant_id,session.table_id,session.session_id,body.type]);res.status(201).json(q.rows[0])}catch(e){console.error(e);res.status(400).json({error:'Could not create request'})}});
app.listen(process.env.PORT||10000,()=>console.log('API running'));